
development:
  adapter: mysql2
  database: perf_development
  pool: 10
  timeout: 5000
  host: localhost
  username: root
  password: Qwerty123!

staging:
  adapter: mysql2
  database: perf_staging
  pool: 10
  timeout: 5000
  host: localhost
  username: root
  password: Qwerty123!